### ISSUE TITLE
00-Login app crashes

### ISSUE THREAD

**Issue by dwatrous** [auth0-samples/auth0-android-sample#60] opened 2018-01-15 23:42 UTC
I'm using the latest version of Android studio and try to get the 00-Login sample app up and running. The app loads, but when I click "SHOW LOG IN", the app crashes. Based on the log output below it seems to not be able to find the auth0 libraries.

I opened the unmodified code from github in Android Studio to run this.

```
01/15 17:37:46: Launching app
$ adb shell am start -n "com.auth0.samples/com.auth0.samples.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 7618 on device emulator-5554
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/InstantRun: starting instant run server: is main process
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.auth0.samples.MainActivity$2>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/auth0/android/provider/AuthCallback;
I/zygote:     at java.lang.Object java.lang.Class.newInstance() (Class.java:-2)
I/zygote:     at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1174)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2669)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.auth0.android.provider.AuthCallback" on path: DexPathList[[zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/base.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_0_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_1_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_2_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_3_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_4_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_5_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_6_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_7_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_8_apk.apk", zip
I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote:     at java.lang.Object java.lang.Class.newInstance() (Class.java:-2)
I/zygote:     at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1174)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2669)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.auth0.samples.MainActivity$2>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/auth0/android/provider/AuthCallback;
I/zygote:     at java.lang.Object java.lang.Class.newInstance() (Class.java:-2)
I/zygote:     at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1174)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2669)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.auth0.android.provider.AuthCallback" on path: DexPathList[[zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/base.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_0_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_1_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_2_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_3_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_4_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_5_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_6_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_7_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_8_apk.apk", zip
I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote:     at java.lang.Object java.lang.Class.newInstance() (Class.java:-2)
I/zygote:     at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1174)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2669)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.auth0.samples.MainActivity$2>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/auth0/android/provider/AuthCallback;
I/zygote:     at java.lang.Object java.lang.Class.newInstance() (Class.java:-2)
I/zygote:     at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1174)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2669)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.auth0.android.provider.AuthCallback" on path: DexPathList[[zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/base.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_0_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_1_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_2_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_3_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_4_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_5_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_6_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_7_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_8_apk.apk", zip
I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote:     at java.lang.Object java.lang.Class.newInstance() (Class.java:-2)
I/zygote:     at android.app.Activity android.app.Instrumentation.newActivity(java.lang.ClassLoader, java.lang.String, android.content.Intent) (Instrumentation.java:1174)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2669)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
D/OpenGLRenderer: HWUI GL Pipeline
I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0x9c0fcd80: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0x9c0fcd80: ver 2 0 (tinfo 0x9d363d40)
D/EGL_emulation: eglMakeCurrent: 0x9c0fcd80: ver 2 0 (tinfo 0x9d363d40)
V/StudioProfiler: StudioProfilers agent attached.
V/StudioProfiler: Acquiring Application for Events
V/StudioProfiler: Transformed class: java/net/URL
W/zygote: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
V/StudioProfiler: Memory control stream started.
V/StudioProfiler: Live memory tracking disabled.
V/StudioProfiler: Live memory tracking enabled.
V/StudioProfiler: JNIEnv not attached
V/StudioProfiler: Loaded classes: 5089
V/StudioProfiler: Tracking initialization took: 542442210ns
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.auth0.samples, PID: 7618
                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/auth0/android/Auth0;
                      at com.auth0.samples.MainActivity.login(MainActivity.java:43)
                      at com.auth0.samples.MainActivity.access$000(MainActivity.java:23)
                      at com.auth0.samples.MainActivity$1.onClick(MainActivity.java:36)
                      at android.view.View.performClick(View.java:6294)
                      at android.view.View$PerformClick.run(View.java:24770)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.auth0.android.Auth0" on path: DexPathList[[zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/base.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_0_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_1_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_2_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_3_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_4_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_5_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_6_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_7_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_8_apk.apk", zip file "/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.auth0.samples-4zZI_g2IWVjQbxKC_KhNew==/lib/x86, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at com.auth0.samples.MainActivity.login(MainActivity.java:43) 
                      at com.auth0.samples.MainActivity.access$000(MainActivity.java:23) 
                      at com.auth0.samples.MainActivity$1.onClick(MainActivity.java:36) 
                      at android.view.View.performClick(View.java:6294) 
                      at android.view.View$PerformClick.run(View.java:24770) 
                      at android.os.Handler.handleCallback(Handler.java:790) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6494) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
Application terminated.

```

**Comment by jimmyjames** [comment] 2019-06-24 14:11
Hi @dwatrous were you able to find a solution for this? Given the issue is pretty old and the sample has changed since reporting, I'm going to close this issue. Don't hesitate to reopen or create a new issue if you are still experiencing the issue.

**Closed by jimmyjames** 2019-06-24 14:11 UTC
